const content = {
  navbar: {
    items: [
      { value: 'Home', href: '/' },
      { value: 'Music', href: '/music' },
      { value: 'Videos', href: '/videos' },
      { value: 'Contact', href: '/contact' },
    ],
  },
  homePage: {},
  videosPage: {
    title: 'Videos',
    videoIds: [
      '-oAWpeiwy7g',
      'HTualFAdKEU',
      'qpsJCFcK0CA',
      'LYBIE7ipVj0',
      'kjZxn1bg-zI',
      'sIu1hAUibNc',
      'VH-F3YbUJ4g',
      'mhjiBJ0JrZA',
      'AcKgrA1Y3KM',
      '0pLgUGSCx7c',
      'GQ9HHQMPrxc',
      'ZOSYPqWgLWk',
      '_TOK9XxNlAg',
      'pIdj9AaBJB0',
      'U1EYTP--INE',
      'mXDugfZGu2M',
      '6ts_xFzQY0U',
      '6yZq_1G6Zcg',
      'HIH9Z7__CXs',
      'JtWfN9KcHqE',
      'XrAr5932Bys',
      'unmKskAgymg',
      '1aq8HzTQKMs',
      'E2yiTO0hh2M',
      'OXB1KmigQTo',
      'hwT4W4Un0uQ',
      'vObom3HPldk',
      'yVAmurZHhUk',
    ],
  },
};
export default content;
